class Question {
  final int id, answer;
  final String question;
  final List<String> options;

  Question({this.id, this.question, this.answer, this.options});
}

// Spanish Beginners
const List sample_data = [
  {
    "id": 1,
    "question": "What is the correct translation for \"telephone\"?",
    "options": ['el agua', 'una bicicleta', 'el teléfono', 'un paraguas'],
    "answer_index": 2,
  },
  {
    "id": 2,
    "question": "How do you say \"Good morning\"?",
    "options": ['Buenas tardes', 'Adios', 'Buenas noches', 'Buenos días'],
    "answer_index": 3,
  },
  {
    "id": 3,
    "question": "How do you say \"Good afternoon\"?",
    "options": ['Buenas tardes', 'Buenos días', 'Adios', 'Buenas noches'],
    "answer_index": 0,
  },
  {
    "id": 4,
    "question": "How do you say \"Good evening\"?",
    "options": ['Buenas noches', 'Muchas gracias', 'Adios', 'unas llaves'],
    "answer_index": 0,
  },
  {
    "id": 5,
    "question": "What is the correct translation for \"Please\"?",
    "options": ['izquierda', 'Por favor', 'Perdón', 'Hola'],
    "answer_index": 1,
  },
  {
    "id": 6,
    "question": "How do you say \"Thank You\"?",
    "options": ['Adios', 'Gracias', 'Perdón', 'derecha'],
    "answer_index": 1,
  },
  {
    "id": 7,
    "question": "What is the correct translation for \"Thank you very much\"?",
    "options": ['No sé', 'Muchas gracias', '¡Perdón!', '¡Salud!'],
    "answer_index": 1,
  },
  {
    "id": 8,
    "question": "How do you say \"Sorry\"?",
    "options": ['Por favor', 'Perdón', 'No sé', 'Gracias'],
    "answer_index": 1,
  },
  {
    "id": 9,
    "question": "How do you say \"Hello\"?",
    "options": ['No sé', 'Por favor', 'Gracias', 'Hola'],
    "answer_index": 3,
  },
  {
    "id": 10,
    "question": "How do you say \"Good-bye\"?",
    "options": ['Buenas noches', 'izquierda', '¿Dónde está la playa?', 'Adios'],
    "answer_index": 3,
  },
  {
    "id": 11,
    "question": "What is the correct translation for \"Monday\"?",
    "options": ['Lunes', 'Martes', '¡Perdón!', '¡Salud!'],
    "answer_index": 0,
  },
  {
    "id": 12,
    "question": "What is the correct translation for \"izquierda\"?",
    "options": ['Hello', 'Train', 'Left', 'Right'],
    "answer_index": 2,
  },
  {
    "id": 13,
    "question": "What is the correct translation for \"right\"?",
    "options": ['tres', 'un tren', 'izquierda', 'derecha'],
    "answer_index": 3,
  },
  {
    "id": 14,
    "question": "How do you say \"water\"?",
    "options": ['el agua', 'un plato', 'la leche', 'un tazón'],
    "answer_index": 0,
  },
  {
    "id": 15,
    "question": "How do you say \"milk\"?",
    "options": ['el agua', 'un plato', 'la leche', 'un tazón'],
    "answer_index": 2,
  },
  {
    "id": 16,
    "question": "What is the correct translation for \"hospital\"?",
    "options": ['unas aspirinas', 'un hospital', 'una casa', 'el agua'],
    "answer_index": 1,
  },
  {
    "id": 17,
    "question": "How do you say \"taxi\"?",
    "options": ['un hospital', 'un taxi', 'un coche', 'una cama'],
    "answer_index": 1,
  },
  {
    "id": 18,
    "question": "What is the correct translation for \"credit card\"?",
    "options": ['un sobre', 'una tarjeta de crédito', 'un periódico', 'un libro'],
    "answer_index": 1,
  },
  {
    "id": 19,
    "question": "What is the correct translation for \"keys\"?",
    "options": ['unas llaves', 'unas tostadas', 'una cama', 'un cuchillo'],
    "answer_index": 0,
  },
  {
    "id": 20,
    "question": "What is the correct translation for \"bicycle\"?",
    "options": ['una cama', 'una bicicleta', 'un coche', 'un plato'],
    "answer_index": 1,
  },
  {
    "id": 21,
    "question": "How do you say \"car\"?",
    "options": ['un cuchillo', 'un tren', 'un coche', 'un barco'],
    "answer_index": 2,
  },
  {
    "id": 22,
    "question": "How do you say \"train\"?",
    "options": ['un coche', 'un barco', 'un avión', 'un tren'],
    "answer_index": 3,
  },
  {
    "id": 23,
    "question": "How do you say \"The girl\"?",
    "options": ['la mujer', 'el hombre', 'la nina', 'el nino'],
    "answer_index": 2,
  },
  {
    "id": 24,
    "question": "What is the correct translation for \"ship\"?",
    "options": ['un barco', 'una bicicleta', 'un tren', 'un avión'],
    "answer_index": 0,
  },
  {
    "id": 25,
    "question": "How do you say \"beach\"?",
    "options": ['un pasaporte', 'el pescado', 'la playa', 'una casa'],
    "answer_index": 2,
  },
  {
    "id": 26,
    "question": "What is the correct translation for \"house\"?",
    "options": ['un hospital', 'el baño', 'una casa', 'un hotel'],
    "answer_index": 2,
  },
  {
    "id": 27,
    "question": "What is the correct translation for \"hotel\"?",
    "options": ['un hotel', 'una casa', 'la playa', 'una silla'],
    "answer_index": 0,
  },
  {
    "id": 28,
    "question": "What is the correct translation for \"bread\"?",
    "options": ['el pescado', 'una cebolla', 'el pan', 'unas patatas'],
    "answer_index": 2,
  },
  {
    "id": 29,
    "question": "What is the correct translation for \"glass\"?",
    "options": ['un tazón', 'un vaso', 'la coca cola', 'una taza'],
    "answer_index": 1,
  },
  {
    "id": 30,
    "question": "What is the correct translation for \"fish\"?",
    "options": ['una cebolla', 'el pescado', 'el maíz', 'una ciruela'],
    "answer_index": 1,
  },
  {
    "id": 31,
    "question": "What is the correct translation for \"sweet corn\"?",
    "options": ['el maíz', 'unas fresas', 'unas frambuesas', 'unas manzanas'],
    "answer_index": 0,
  },
  {
    "id": 32,
    "question": "What is the correct translation for \"mango\"?",
    "options": ['unas frambuesas', 'un mango', 'unas fresas', 'un plátano'],
    "answer_index": 1,
  },
  {
    "id": 33,
    "question": "What is the correct translation for \"banana\"?",
    "options": ['unas patatas', 'unas frambuesas', 'el queso', 'un plátano'],
    "answer_index": 3,
  },
  {
    "id": 34,
    "question": "What is the correct translation for \"apples\"?",
    "options": ['una naranja', 'un pomelo', 'unas manzanas', 'unas fresas'],
    "answer_index": 2,
  },
  {
    "id": 35,
    "question": "What is the correct translation for \"strawberry\"?",
    "options": ['una naranja', 'una ciruela', 'unas fresas', 'un pomelo'],
    "answer_index": 2,
  },
  {
    "id": 36,
    "question": "What is the correct translation for \"onion\"?",
    "options": ['unos champiñones', 'un pepino', 'la mantequilla', 'una cebolla'],
    "answer_index": 3,
  },
  {
    "id": 37,
    "question": "What is the correct translation for \"grapefruit\"?",
    "options": ['una cebolla', 'un pomelo', 'el queso', 'unas frambuesas'],
    "answer_index": 1,
  },
  {
    "id": 38,
    "question": "What is the correct translation for \"raspberries\"?",
    "options": ['el queso', 'una circuela', 'unas frambuesas', 'un pomelo'],
    "answer_index": 2,
  },
  {
    "id": 39,
    "question": "What is the correct translation for \"cucumber\"?",
    "options": ['un pepino', 'una camote', 'un tomate', 'un pomelo'],
    "answer_index": 0,
  },
  {
    "id": 40,
    "question": "What is the correct translation for \"mushrooms\"?",
    "options": ['unos champiñones', 'una circuela', 'el queso', 'un pomelo'],
    "answer_index": 0,
  },
  {
    "id": 41,
    "question": "What is the correct translation for \"green\"?",
    "options": ['rosa', 'blanco', 'amarillo', 'verde'],
    "answer_index": 3,
  },
  {
    "id": 42,
    "question": "What is the correct translation for \"yellow\"?",
    "options": ['amarillo', 'marrón', 'negro', 'verde'],
    "answer_index": 0,
  },
  {
    "id": 43,
    "question": "What is the correct translation for \"white\"?",
    "options": ['negro', 'rojo', 'azul', 'blanco'],
    "answer_index": 3,
  },
  {
    "id": 44,
    "question": "What is the correct translation for \"pink\"?",
    "options": ['rojo', 'rosa', 'verde', 'amarillo'],
    "answer_index": 1,
  },
  {
    "id": 45,
    "question": "How do you say \"Where is the shop\"?",
    "options": ['¿Dónde está la tienda?', '¿Dónde está la playa?', '¿Dónde está mi pasaporte?', '¿Dónde está el profesor?'],
    "answer_index": 0,
  },
  {
    "id": 46,
    "question": "How do you say \"Where is the beach\"?",
    "options": ['¿Donde está el museo?', '¿Dónde está la estación?', '¿Dónde está la tienda?', '¿Dónde está la playa?'],
    "answer_index": 3,
  },
  {
    "id": 47,
    "question": "How do you say \"I need a doctor\"?",
    "options": ['¿Dónde está la playa?', 'La cuenta, por favor', 'No sé', 'Necesito un médico'],
    "answer_index": 3,
  },
  {
    "id": 48,
    "question": "What is the correct translation for \"head\"?",
    "options": ['la pierna', 'el pelo', 'una oreja', 'la cabeza'],
    "answer_index": 3,
  },
  {
    "id": 49,
    "question": "What is the correct translation for \"leg\"?",
    "options": ['la pierna', 'un ojo', 'la nariz', 'la cabeza'],
    "answer_index": 0,
  },
  {
    "id": 50,
    "question": "What is the correct translation for \"foot\"?",
    "options": ['un ojo', 'el pie', 'la pierna', 'una oreja'],
    "answer_index": 1,
  },
  {
    "id": 51,
    "question": "What is the correct translation for \"two\"?",
    "options": ['cinco', 'tres', 'dos', 'cuatro'],
    "answer_index": 2,
  },
  {
    "id": 52,
    "question": "What is the correct translation for \"four\"?",
    "options": ['uno', 'siete', 'ocho', 'cuatro'],
    "answer_index": 3,
  },
  {
    "id": 53,
    "question": "What is the correct translation for \"ten\"?",
    "options": ['diez', 'dos', 'nueve', 'once'],
    "answer_index": 0,
  },
  {
    "id": 54,
    "question": "How do you say \"five o'clock\"?",
    "options": ['las ocho en punto', 'las diez en punto', 'las cinco en punto', 'las seis en punto'],
    "answer_index": 2,
  },
  {
    "id": 55,
    "question": "How do you say \"six o'clock\"?",
    "options": ['las tres en punto', 'las cinco en punto', 'las siete en punto', 'las seis en punto'],
    "answer_index": 3,
  },
  {
    "id": 56,
    "question": "What is the correct translation for \"pen\"?",
    "options": ['un paraguas', 'un lápiz', 'un bolígrafo', 'un reloj'],
    "answer_index": 2,
  },
  {
    "id": 57,
    "question": "What is the correct translation for \"pencil\"?",
    "options": ['un paraguas', 'un lápiz', 'un bolígrafo', 'un reloj'],
    "answer_index": 1,
  },
  {
    "id": 58,
    "question": "What is the correct translation for \"book\"?",
    "options": ['un sobre', 'un libro', 'un bolígrafo', 'un sombrero'],
    "answer_index": 1,
  },
  {
    "id": 59,
    "question": "What is the correct translation for \"toothpaste\"?",
    "options": ['un cepillo de dientes', 'un cepillo del pelo', 'una toalla', 'la pasta de dientes'],
    "answer_index": 3,
  },
  {
    "id": 60,
    "question": "What is the correct translation for \"toothbrush\"?",
    "options": ['un cepillo de dientes', 'un cepillo del pelo', 'una toalla', 'la pasta de dientes'],
    "answer_index": 0,
  },
  {
    "id": 61,
    "question": "What is the correct translation for \"Tuesday\"?",
    "options": ['Lunes', 'Miercoles', 'Martes', 'Sabado'],
    "answer_index": 2,
  },
  {
    "id": 62,
    "question": "What is the correct translation for \"Wednesday\"?",
    "options": ['Domingo', 'Miercoles', 'Martes', 'Sabado'],
    "answer_index": 1,
  },
  {
    "id": 63,
    "question": "What is the correct translation for \"Thursday\"?",
    "options": ['Jueves', 'Miercoles', 'Martes', 'Sabado'],
    "answer_index": 0,
  },
  {
    "id": 64,
    "question": "What is the correct translation for \"Friday\"?",
    "options": ['Jueves', 'Viernes', 'Miercoles', 'Sabado'],
    "answer_index": 1,
  },
  {
    "id": 65,
    "question": "What is the correct translation for \"Saturday\"?",
    "options": ['Jueves', 'Viernes', 'Domingo', 'Sabado'],
    "answer_index": 3,
  },
  {
    "id": 66,
    "question": "What is the correct translation for \"Sunday\"?",
    "options": ['Jueves', 'Domingo', 'Miercoles', 'Sabado'],
    "answer_index": 1,
  },
  {
    "id": 67,
    "question": "What is the correct translation for \"Queso\"?",
    "options": ['Turkey', 'Chicken', 'Cheese', 'Right'],
    "answer_index": 2,
  },
  {
    "id": 68,
    "question": "What is the correct translation for \"Bueno\"?",
    "options": ['Funny', 'Good', 'Fun', 'Open'],
    "answer_index": 1,
  },
  {
    "id": 69,
    "question": "What is the correct translation for \"Sesenta\"?",
    "options": ['Sixty', 'Open', 'Eighty', 'Seventy'],
    "answer_index": 0,
  },
  {
    "id": 70,
    "question": "What is the correct translation for \"Caja sorpresa\"?",
    "options": ['Jumbo', 'Open', 'Huh', 'Jack-in-the-box'],
    "answer_index": 3,
  },
  {
    "id": 71,
    "question": "What is the correct translation for \"tomato\"?",
    "options": ['un pepino', 'una tomate', 'una camote', 'un pomelo'],
    "answer_index": 1,
  },
  {
    "id": 72,
    "question": "What is the correct translation for \"cabbage\"?",
    "options": ['una col', 'una tomate', 'una camote', 'una coliflor'],
    "answer_index": 0,
  },
  {
    "id": 73,
    "question": "What is the correct translation for \"broccoli\"?",
    "options": ['una col', 'una coliflor', 'un brócoli', 'un pomelo'],
    "answer_index": 2,
  },
  {
    "id": 74,
    "question": "What is the correct translation for \"lettuce\"?",
    "options": ['una col', 'una coliflor', 'un brócoli', 'una lechuga'],
    "answer_index": 3,
  },
  {
    "id": 75,
    "question": "What is the correct translation for \"pepper\"?",
    "options": ['una col', 'un pimiento', 'un brócoli', 'una lechuga'],
    "answer_index": 1,
  },
  {
    "id": 76,
    "question": "What is the correct translation for \"pea\"?",
    "options": ['una col', 'un pimiento', 'un brócoli', 'un chícharro'],
    "answer_index": 3,
  },
  {
    "id": 77,
    "question": "What is the correct translation for \"the bell rings\"?",
    "options": ['la ventana', 'un triangulo', 'el ombligo', 'la campana suena'],
    "answer_index": 3,
  },
  {
    "id": 78,
    "question": "What is the correct translation for \"horse\"?",
    "options": ['el caballo', 'la botella', 'el martillo', 'el regalo'],
    "answer_index": 0,
  },
  {
    "id": 79,
    "question": "What is the correct translation for \"meanwhile\"?",
    "options": ['diciembre', 'suelta de', 'mientras', 'enero'],
    "answer_index": 2,
  },
  {
    "id": 80,
    "question": "What is the correct translation for \"dog\"?",
    "options": ['el pelo', 'el gato', 'el cuello', 'el perro'],
    "answer_index": 3,
  },
  {
    "id": 81,
    "question": "What is the correct translation for \"cat\"?",
    "options": ['el pelo', 'el gato', 'el cuello', 'el perro'],
    "answer_index": 1,
  },
  {
    "id": 82,
    "question": "What is the correct translation for \"march\"?",
    "options": ['marzo', 'mayo', 'enero', 'abril'],
    "answer_index": 0,
  },
  {
    "id": 83,
    "question": "What is the correct translation for \"febuary\"?",
    "options": ['enero', 'octubre', 'agosto', 'febrero'],
    "answer_index": 3,
  },
  {
    "id": 84,
    "question": "What is the correct translation for \"april\"?",
    "options": ['junio', 'julio', 'marzo', 'abril'],
    "answer_index": 3,
  },
  {
    "id": 85,
    "question": "What is the correct translation for \"july\"?",
    "options": ['junio', 'julio', 'mayo', 'marzo'],
    "answer_index": 1,
  },
  {
    "id": 86,
    "question": "What is the correct translation for \"Age\"?",
    "options": ['La edad', 'Un abrazo', 'La toalla', 'Un beso'],
    "answer_index": 0,
  },
  {
    "id": 87,
    "question": "What is the correct translation for \"Kiss\"?",
    "options": ['La edad', 'Un abrazo', 'La tolla', 'Un beso'],
    "answer_index": 3,
  },
  {
    "id": 88,
    "question": "How do you say \"¿Cómo se llama?\"?",
    "options": ['How is it going?', 'What is your name?', 'Are you okay?', 'Where are you from?'],
    "answer_index": 1,
  },
  {
    "id": 89,
    "question": "How do you say \"¿De dónde es usted?\"?",
    "options": ['Where are you from?', 'Where is the bathroom?', 'Really?', 'How are you?'],
    "answer_index": 0,
  },
  {
    "id": 90,
    "question": "How do you say \"¿De dónde eres?\"?",
    "options": ['Really?', 'How is it going?', 'Where is the bathroom?', 'Where are you from?'],
    "answer_index": 3,
  },
  {
    "id": 91,
    "question": "How do you say \"¿Que tal?\"?",
    "options": ['Really?', 'How is it going?', 'Where is the bathroom?', 'Where are you from?'],
    "answer_index": 1,
  },
  {
    "id": 92,
    "question": "How do you say \"¿Tu crees?\"?",
    "options": ['Do you think so?', 'How much is it?', 'What is it?', 'Where are you from?'],
    "answer_index": 0,
  },
  {
    "id": 93,
    "question": "How do you say \"¿De veras?\"?",
    "options": ['Really?', 'Huh?', 'Do you think so?', 'How much is it?'],
    "answer_index": 0,
  },
  {
    "id": 94,
    "question": "How do you say \"¿Cuanto cuesta?\"?",
    "options": ['Really?', 'Huh?', 'Do you think so?', 'How much is it?'],
    "answer_index": 3,
  },
  {
    "id": 95,
    "question": "How do you say \"No comprendo\"?",
    "options": ['I need a Doctor', 'Not at all', 'I\'m sorry', 'I don\'t understand'],
    "answer_index": 3,
  },
  {
    "id": 96,
    "question": "How do you say \"De ninguna manera\"?",
    "options": ['I need a Doctor', 'No way', 'Same here', 'I don\'t understand'],
    "answer_index": 1,
  },
  {
    "id": 97,
    "question": "How do you say \"Yo iqual\"?",
    "options": ['I need a Doctor', 'Not at all', 'Same here', 'I don\'t understand'],
    "answer_index": 2,
  },
  {
    "id": 98,
    "question": "How do you say \"Me gusta\"?",
    "options": ['I\' sorry', 'Not at all', 'I don\'t speak Spanish', 'I like it'],
    "answer_index": 3,
  },
  {
    "id": 99,
    "question": "How do you say \"Mucho gusto\"?",
    "options": ['Nice to meet you', 'Not at all', 'I don\'t speak Spanish', 'I like it'],
    "answer_index": 0,
  },
  {
    "id": 100,
    "question": "How do you say \"No hablo espanol\"?",
    "options": ['Nice to meet you', 'Not at all', 'I don\'t speak Spanish', 'I like it'],
    "answer_index": 2,
  },
];


